### ISSUE TITLE
Feedback week 1 - Mokhtar Akle

### ISSUE THREAD

**Issue by MokhtarAkle** [jtoufik/Stekjesbieb#1]
Wireframe en flow zien er goed uit, de pagina heeft 1 functie en het is duidelijk en makkelijk om je doel te halen. De voorlopige HTML is erg schoon en semantisch correct opgebouwd. Verder is de huidige webpagina hetzelfde opgebouwd als de wireframe dus ik zou zo door gaan.

**Comment by JalalToufik** [comment]
Thanks man! jij bent ook goed bezig!

> Wireframe en flow zien er goed uit, de pagina heeft 1 functie en het is duidelijk en makkelijk om je doel te halen. De voorlopige HTML is erg schoon en semantisch correct opgebouwd. Verder is de huidige webpagina hetzelfde opgebouwd als de wireframe dus ik zou zo door gaan.
